const constants = {
  ADD_COLOR: "ADD_COLOR",
  RATE_COLOR: "RATE_COLOR",
  REMOVE_COLOR: "REMOVE_COLOR",
  SORT_COLORS: "SORT_COLORS",
  MOVE_CARD: "MOVE_CARD",
  TOGGLE_DONE_CARD: "TOGGLE_DONE_CARD",
}

export default constants